### ISSUE TITLE
Side Menu does not appear when Window became smaller

### ISSUE THREAD

**Issue by felippeferrao** [primefaces/sigma-react#17]
Wen we change the width´s window, the side menu do not appear anymore.
Some recent changes on Style made this things happen.

**Comment by mwesigab** [comment]
Hey @felippeferrao I fixed this issue by editing the "_responsive.scss" file under src/layout/sass path. The issue is that the classname "layout-mobile-sidebar-active" was not put in the correct media query. I have attached an edited file. Check it out in case you haven't fixed it yet.
[_responsive.zip](https://github.com/primefaces/sigma-react/files/5679806/_responsive.zip)

**Comment by felippeferrao** [comment]
> Hey @felippeferrao I fixed this issue by editing the "_responsive.scss" file under src/layout/sass path. The issue is that the classname "layout-mobile-sidebar-active" was not put in the correct media query. I have attached an edited file. Check it out in case you haven't fixed it yet.
> [_responsive.zip](https://github.com/primefaces/sigma-react/files/5679806/_responsive.zip)

Hey, Thanks for your help.. It solved for me!
Best regards

**Comment by mwesigab** [comment]
I'm glad I was useful. Thanks

**Comment by windgaucho** [comment]
> Hey @felippeferrao I fixed this issue by editing the "_responsive.scss" file under src/layout/sass path. The issue is that the classname "layout-mobile-sidebar-active" was not put in the correct media query. I have attached an edited file. Check it out in case you haven't fixed it yet.
> [_responsive.zip](https://github.com/primefaces/sigma-react/files/5679806/_responsive.zip)

Thank you very much @mwesigab that help me too !!

**Comment by mwesigab** [comment]
> > Hey @felippeferrao I fixed this issue by editing the "_responsive.scss" file under src/layout/sass path. The issue is that the classname "layout-mobile-sidebar-active" was not put in the correct media query. I have attached an edited file. Check it out in case you haven't fixed it yet.
> > [_responsive.zip](https://github.com/primefaces/sigma-react/files/5679806/_responsive.zip)
> 
> Thank you very much @mwesigab that help me too !!

My pleasure 👍

**Comment by HammacheAbir** [comment]
> Hey @felippeferrao I fixed this issue by editing the "_responsive.scss" file under src/layout/sass path. The issue is that the classname "layout-mobile-sidebar-active" was not put in the correct media query. I have attached an edited file. Check it out in case you haven't fixed it yet.
> [_responsive.zip](https://github.com/primefaces/sigma-react/files/5679806/_responsive.zip)

Thanks a lot it works

**Comment by mwesigab** [comment]
> > Hey @felippeferrao I fixed this issue by editing the "_responsive.scss" file under src/layout/sass path. The issue is that the classname "layout-mobile-sidebar-active" was not put in the correct media query. I have attached an edited file. Check it out in case you haven't fixed it yet.
> > [_responsive.zip](https://github.com/primefaces/sigma-react/files/5679806/_responsive.zip)
> 
> Thanks a lot it works

My pleasure

**Comment by SouzaeCambos** [comment]
Than

> Hey @felippeferrao I fixed this issue by editing the "_responsive.scss" file under src/layout/sass path. The issue is that the classname "layout-mobile-sidebar-active" was not put in the correct media query. I have attached an edited file. Check it out in case you haven't fixed it yet.
> [_responsive.zip](https://github.com/primefaces/sigma-react/files/5679806/_responsive.zip)

Thanks

**Comment by TolgaYigit** [comment]
I tried to fix this issue for both overlay and static menu type in this PR #20
