### ISSUE TITLE
Sigma-React crashing upon startup because of an error in PrismJS

### ISSUE THREAD

**Issue by nemethmik** [primefaces/sigma-react#22]
I am new fan of the Primefaces products and I am evaluating Primereact. I have just cloned Sigma-React and when I started it simply crashed because of an error in PrismJS, which is used for code highlight. I removed PrismJS and modified two files to remove references, and everything worked fine. So not a major issue at all, I just wanted to let you know:
see https://youtu.be/IwpRIwJD5ys?t=777

**Comment by mertsincan** [comment]
Thanks a lot, @nemethmik ;)
